### ISSUE TITLE
page_data approach does not seem to work anymore

### ISSUE THREAD

**Issue by ashishb** [amustafa/docsend_scraper#2]
It seems docsend has changed its API. `https://docsend.com/view/<redacted>/page_data/1` works but `https://docsend.com/view/<redacted>/page_data/2` as well as `https://docsend.com/view/<redacted>/page_data/3` gives 403 forbidden for a particular file I tried. The file had more than 3 pages and your tool correctly calculated the number of pages.

**Comment by amustafa** [comment]
@ashishb I can take a look this weekend and see if this is a simple fix but this was a one-off project I built for an interview so I'm probably not going to spend a whole lot of time fixing it if it's very difficult. I'd be happy to accept a PR if getting this project running is important to you.

**Comment by ashishb** [comment]
> I'd be happy to accept a PR if getting this project running is important to you.

I tried, I could not figure out for sure as to what's wrong though. Probably docsend changed its APIs.
